import { Mesh } from "three"

export interface SolarPlanet {
    id: string,
    name: string,
    _name: string,
    yRot: number,
    zRot?: number,
    xRot?: number,
    text: string,
    radius?: string,
    mesh?: Mesh,
    temp1?: string,
    temp2?: string,
    sound?: HTMLAudioElement,
}

export const SSConfig: {
    items: SolarPlanet[],
    rotationSpeed: number,
    rotSpeedMultiplier: number,
} = {
    items: [
        {
            id: '1',
            name: 'Меркурий',
            _name: 'Mercury',
            yRot: -3,
            text: 'Меркурий - самая ближняя к Солнцу планета в Солнечной системе, известная своим малым размером. ',
            radius: '2439',
            temp1: '-173',
            temp2: '+427',
            sound: new Audio("assets/audio/barley.mp3"),
        },
        {
            id: '2',
            name: 'Венера',
            _name: 'Venus',
            yRot: -2.4,
            text: 'Венера - вторая планета от Солнца, известная своим плотным атмосферным покровом.  ',
            radius: '6051',
            temp2: '+462',
            sound: new Audio("assets/audio/barley.mp3"),
        },
        {
            id: '3',
            name: 'Earth',
            _name: 'Earth',
            yRot: -2,
            text: 'Земля - третья планета от Солнца и наш дом во Вселенной.  ',
            // radius: 6371,
            // temp1: -89,
            // temp2: +56,
            sound: new Audio("assets/audio/barley.mp3"),
        },
        {
            id: '4',
            name: 'Mars',
            _name: 'Mars',
            yRot: 1.5,
            text: 'Марс - четвёртая планета от Солнца, также известная как "Красная планета". ',
            // radius: 2439,
            // temp1: -87,
            // temp2: +5,
        },
        {
            id: '6',
            name: 'Jupiter',
            _name: 'Jupiter',
            yRot: -1.4,
            text: 'Юпитер - пятая планета от Солнца и крупнейшая планета в Солнечной системе. Юпитер обладает сильным магнитным полем, значительно превышающим магнитное поле Земли.  ',
            // radius: 69911 ,
            // temp1: -145,
            // temp2: +0,
        },
        {
            id: '7',
            name: 'Saturn',
            _name: 'Saturn',
            yRot: 1.3,
            text: 'Сатурн - шестая планета от Солнца, известная своими кольцами, являющимися одной из самых заметных и уникальных черт этой планеты.  ',
            // radius: 58232,
            // temp1: -178,
            // temp2: +178,
        },
        {
            id: '9',
            name: 'Uran',
            _name: 'Uran',
            yRot: -1,
            text: 'Уран - седьмая планета от Солнца, известная своим характерным голубым оттенком и наклоном своей оси вращения.  ',
            // radius: 25362 ,
            // temp1: -224,
        },
        {
            id: '10',
            name: 'Нептун',
            _name: 'Neptune',
            yRot: 1,
            text: 'Нептун - восьмая и самая дальняя планета от Солнца, которая славится своей голубой окраской и атмосферными бурями. ',
            radius: '24622' ,
            temp1: '-218',
        },
        {
            id: '11',
            name: 'Sun',
            _name: 'sun',
            yRot: 0,
            zRot: .5,
            text: 'Солнце - центральная звезда Солнечной системы и источник света и тепла для нашей планеты Земля. Солнце является плазменным шаром, состоящим в основном из водорода и гелия, и его энергия происходит из ядерных реакций, где водород превращается в гелий. ',
            radius:  '696340',
            temp2: '+5500',
        },
        {
            id: '12',
            name: 'Moon',
            _name: 'moon',
            yRot: -1,
            text: 'Луна - единственный естественный спутник Земли, орбитирующий вокруг неё.  ',
            // radius: 3474,
            // temp1: -173,
            // temp2: +127,
        },
    ],
    rotationSpeed: 0.001,
    rotSpeedMultiplier: 0.002,
}